name: ccs-timing
channels:
- defaults
- conda-forge
dependencies:
- python=3.6
- matplotlib=2.2
- numpy
- pandas=0.23
- jupyter
- seaborn=0.8
- nb_conda_kernels

- pip:
  - ghgforcing==0.1.7.1
  - watermark
